---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "test"
host: "localhost:8040"
basePath: "/services"
schemes:
- "http"
paths:
  /V1/customers/1:
    get:
      tags:
      - "General"
      summary: "agent/account/SD"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Successful response"
          schema:
            type: "object"
